# See also https://goreleaser.com/customization/build/

before:
  hooks:
    - go generate ./...

builds:
  -
    # Path to main.go file or main package.
    # Default is `.`.
    main: ./cmd/kubectl-debugpod/main.go

    env:
      - CGO_ENABLED=0
